language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install flake8
script:
  - make test
  # Manually run test on Python 2 as well
  - python -m unittest discover
notifications:
  email:
    - phihag@phihag.de
