.TH MOCKMAIL "1" "January 2012" "mockmail" "User Commands"
.SH NAME
mockmail \- SMTP test server
.SH SYNOPSIS
.B mockmail
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-c\fR FILE, \fB\-\-config\fR=\fIFILE\fR
JSON configuration file to load
.TP
\fB\-d\fR, \fB\-\-daemonize\fR
Run mockmail in the background. Overwrites
configuration
.TP
\fB\-i\fR, \fB\-\-interactive\fR
Run mockmail in the foreground. Overwrites
configuration
.TP
\fB\-\-pidfile\fR=\fIPIDFILE\fR
Set pidfile to use. Overwrites configuration
.TP
\fB\-\-ctl\-status\fR
Check whether mockmail service is running.
.TP
\fB\-\-ctl\-start\fR
Start mockmail service.
.TP
\fB\-\-ctl\-stop\fR
Stop mockmail service.
.TP
\fB\-\-quiet\-ctl\fR
Do not print announcement in \fB\-\-ctl\-\fR* operations.
.TP
\fB\-\-dumpconfig\fR
Do not run mockmail, but dump the effective
configuration
.TP
\fB\-\-version\fR
Do not run mockmail, but output the version
.SH "SEE ALSO"
For more information on how to setup mockmail, refer to
the README at:

https://github.com/phihag/mockmail/blob/master/README.md